# Travis config file to build spk package
# Adapted from https://github.com/torrentalle/spksrc/tree/gogs-build
# And https://github.com/jelmerj/spksrc

env:
  global:
    - PKG=plowshare
  matrix:
# 6.1 and 6.2 toolchains
# ARM5 arches
    - SYNOARCH=arch-88f6281-6.1
# ARM7 arches
#     - SYNOARCH=arch-alpine-6.1
#     - SYNOARCH=arch-armada370-6.1
#     - SYNOARCH=arch-armada375-6.1
#     - SYNOARCH=arch-armada38x-6.1
#     - SYNOARCH=arch-armadaxp-6.1
#     - SYNOARCH=arch-comcerto2k-6.1
#     - SYNOARCH=arch-hi3535-6.1
#     - SYNOARCH=arch-ipq806x-6.1
#     - SYNOARCH=arch-monaco-6.1
#    - SYNOARCH=syno-northstarplus-1.1
# ARM8 arches (binary compatible, just build aarch64)
#   - SYNOARCH=arch-rtd1296-6.1
#   - SYNOARCH=arch-armada37xx-6.1
    - SYNOARCH=arch-aarch64-6.1
# PPC arches
#    - SYNOARCH=arch-qoriq-6.1
# x86 arches
#     - SYNOARCH=arch-evansport-6.1
# x64 arches (binary compatible, just build x64)
    - SYNOARCH=arch-apollolake-6.1
#   - SYNOARCH=arch-avoton-6.1
#   - SYNOARCH=arch-braswell-6.1
#   - SYNOARCH=arch-broadwell-6.1
#   - SYNOARCH=arch-broadwellnk-6.2
#   - SYNOARCH=arch-bromolow-6.1
#   - SYNOARCH=arch-cedarview-6.1
#   - SYNOARCH=arch-denverton-6.1
#   - SYNOARCH=arch-dockerx64-6.1
#   - SYNOARCH=arch-grantley-6.1
#   - SYNOARCH=arch-kvmx64-6.1
    - SYNOARCH=arch-x64-6.1
#   - SYNOARCH=arch-x86-6.1
#   - SYNOARCH=arch-x86_64-6.1
#
# 5.2 toolchains
#
#    - SYNOARCH=arch-88f6281-5.2
#    - SYNOARCH=arch-alpine-5.2
#    - SYNOARCH=arch-armada370-5.2
#    - SYNOARCH=arch-armada375-5.2
#    - SYNOARCH=arch-armada38x-5.2
#    - SYNOARCH=arch-armadaxp-5.2
#    - SYNOARCH=arch-avoton-5.2
#    - SYNOARCH=arch-braswell-5.2
#    - SYNOARCH=arch-bromolow-5.2
#    - SYNOARCH=arch-cedarview-5.2
#    - SYNOARCH=arch-comcerto2k-5.2
#    - SYNOARCH=arch-evansport-5.2
#    - SYNOARCH=arch-monaco-5.2
#    - SYNOARCH=arch-ppc853x-5.2
#    - SYNOARCH=arch-qoriq-5.2
#    - SYNOARCH=arch-x64-5.2
#    - SYNOARCH=arch-x86-5.2

# Output is too verbose for TravisCI, so we hide it
# Remove the ">/dev/null" part to debug!
# make arch-$SYNOARCH always return exit code 0.
# The "ls" line is to test if SPK has been build.
script:
  - docker pull synocommunity/spksrc;
  - docker run -it -v `pwd`:/spksrc synocommunity/spksrc /bin/bash -c "cd /spksrc && make setup && cd spk/$PKG && make $SYNOARCH>/dev/null";
  - ls packages/*.spk;

services:
  - docker

cache:
    directories:
     - distrib

notifications:
  email: false

git:
  depth: 1

deploy:
  provider: releases
  api_key:
    secure: Kn+VfZ6Zu0BpGbEavf4lcyTq7yXDem8Ldwawv0bkqVhxO3Z5IO1OU5rj5f6V6or8aJjnEyljUkFn/LldzUyg9Or9w0TyFZCWevTHyWug6On/LkGC4Pypc6l62magJgfJkI8BRgurNxRFN8rjZRAnyIQQGUqKbh1ItG/LeQpE/gVZ/TJYJNGlT4DCPgg+nl9dQeE0P8cr7fHANHFnDruOgYiGtnsXrK2a+NhsrvI2qsaXuPi3JG/ml6Il6ZVRX8Q5tvHzBXOqg4+BQTgq+SHBeAslbGYJsmXaHoFeZi6GdyV2YyFTJCGXzRicXAG/DeebrB24E9M4RFxihhL0k7BNeuY31Er43+PK6hN5ctnyOaSz8utOYTWke+iPcB143EyglBaBRJ9fcz5HtbEaHKKLbAXfTtcS9+2vWZQ/EX2f+BgcKwItcsFEI9G2zFh2+OHKtDYqwIjr8y2FY6GNBmCWCNahUGbFjRKcmPql5gzMhon+z+p8NhsKF42m/SuKJ4hBrHWzHYzaqmduoAVDeEaoH/KOaXRY/jRVXRPsTKB6iWGTMS8NlXW4W5nzvnlxAEkft9RAMlcksPq/7WcS+lyibgIBGIKzAn2IDuwAWFz4/l7xm6YoZY3swq3B9Gbo/9Ao7pRvNQZErDN7g2agmQdqGm34jsgZ7DjyPEEx8PDnI+4=
  file_glob: true
  file: packages/*.spk
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
